apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment

spec:
  replicas: 1
  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: myreactapp

  template:
    metadata:
      labels:
        app: myreactapp

    spec:
      containers:
      - name: myreactapp
        image: 988320610889.dkr.ecr.us-east-1.amazonaws.com/react:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-service

spec:
  type: NodePort
  selector:
    app: myreactapp

  ports:
    - port: 8080
      targetPort: 8080

